{{- if .Values.calendar.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendar-chart.fullname" . }}-calendar
  labels:
    {{- include "calendar-chart.calendar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.calendar.service.type }}
  ports:
    - port: {{ .Values.calendar.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calendar-chart.calendar.selectorLabels" . | nindent 4 }}
{{- end }}

